### ISSUE TITLE
Guacamole

### ISSUE THREAD

**Issue by AlexandreTesser** [vaamonde/ubuntu-2004#18]
Estou enfrentando um problema no Script Guacamole.sh, onde o mesmo não instala o guacd, teria como me ajudar?

checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking whether make supports the include directive... yes (GNU style)
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/home/adami/ubuntu-2004/scripts/guacamole-server-1.5.3':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
make: *** Nenhum alvo indicado e nenhum arquivo make encontrado.  Pare.
make: *** Sem regra para processar o alvo 'install'.  Pare.
mkdir: foi criado o diretório '/var/lib/guacd/'
alterado o dono de '/var/lib/guacd/' de root:root para guacd:guacd
sed: não foi possível ler /etc/systemd/system/guacd.service: Arquivo ou diretório inexistente
Failed to enable unit: Unit file guacd.service does not exist.
Failed to start guacd.service: Unit guacd.service not found.
mkdir: foi criado o diretório '/etc/guacamole'
mkdir: foi criado o diretório '/etc/guacamole/extensions'
mkdir: foi criado o diretório '/etc/guacamole/lib'
--2023-09-21 16:43:31--  https://archive.apache.org/dist/guacamole/1.5.3/binary/guacamole-1.5.3.war

**Comment by vaamonde** [comment]
Olá, as dependências do build-essential geralmente instalo no começo do servidor, vou adicionar na lista das depedências principaus do Guacamole.

**Comment by vaamonde** [comment]
Atualizado os arquivos no Github: https://github.com/vaamonde/ubuntu-2004/blob/main/CHANGELOG - adicionado no arquivo: 00-parametros.sh na linha 1112: https://github.com/vaamonde/ubuntu-2004/blob/main/scripts/00-parametros.sh
